-- =====================================================================
-- V1: core catalogue tables - users, addresses, categories,
--     restaurants, menu_items.
--
-- Conventions
--   * BIGINT identity primary keys.
--   * TIMESTAMPTZ for every timestamp: stores an absolute instant (UTC),
--     so values never shift when the server or client time zone changes.
--   * NUMERIC for money: exact decimal arithmetic, no floating-point error.
--   * Enums stored as VARCHAR + CHECK constraint (see users.role).
--   * Constraint names are explicit (uk_, fk_, ck_, idx_) so error messages
--     and the GlobalExceptionHandler can recognise them.
--
-- Flyway rule: never edit this file after it has been applied anywhere.
-- Schema changes go into a new file (V2__..., V3__...).
-- =====================================================================


-- ---------------------------------------------------------------------
-- users: every account (customer, restaurant owner, admin)
-- ---------------------------------------------------------------------
CREATE TABLE users (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(100) NOT NULL,
    email         VARCHAR(255) NOT NULL,
    -- BCrypt hash (always 60 chars); the plain password is never stored.
    password_hash VARCHAR(100) NOT NULL,
    phone         VARCHAR(20),
    role          VARCHAR(20)  NOT NULL,
    -- Accounts are disabled, never hard-deleted: their orders must stay intact.
    enabled       BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),

    -- The UNIQUE constraint also creates the B-tree index used by login (WHERE email = ?).
    CONSTRAINT uk_users_email UNIQUE (email),
    -- The application lower-cases emails; the database guarantees it, so
    -- "A@x.com" and "a@x.com" can never become two different accounts.
    CONSTRAINT ck_users_email_lowercase CHECK (email = lower(email)),
    CONSTRAINT ck_users_role CHECK (role IN ('CUSTOMER', 'RESTAURANT_OWNER', 'ADMIN'))
);


-- ---------------------------------------------------------------------
-- addresses: delivery addresses, many per user
-- ---------------------------------------------------------------------
CREATE TABLE addresses (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- ON DELETE CASCADE: an address has no meaning without its user.
    user_id     BIGINT       NOT NULL,
    label       VARCHAR(30)  NOT NULL,          -- "Home", "Work"
    line1       VARCHAR(255) NOT NULL,
    line2       VARCHAR(255),
    city        VARCHAR(100) NOT NULL,
    state       VARCHAR(100) NOT NULL,
    postal_code VARCHAR(10)  NOT NULL,
    is_default  BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT fk_addresses_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

-- "List my addresses" filters by user_id. PostgreSQL does NOT index foreign keys automatically.
CREATE INDEX idx_addresses_user_id ON addresses (user_id);

-- Partial unique index: at most ONE default address per user.
-- Only rows WHERE is_default = TRUE are indexed, so a user may have many
-- non-default addresses but a second default is rejected by the database itself.
CREATE UNIQUE INDEX uk_addresses_one_default_per_user ON addresses (user_id) WHERE is_default;


-- ---------------------------------------------------------------------
-- categories: global food categories (Biryani, Pizza, Beverages ...)
-- Shared by all restaurants so "show restaurants that serve Biryani"
-- is one indexed lookup instead of matching free-text names.
-- ---------------------------------------------------------------------
CREATE TABLE categories (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(50)  NOT NULL,
    description VARCHAR(255),
    image_url   VARCHAR(500),
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- Expression index: "Pizza" and "pizza" are the same category.
CREATE UNIQUE INDEX uk_categories_name_lower ON categories (lower(name));


-- ---------------------------------------------------------------------
-- restaurants: each owned by one RESTAURANT_OWNER user
-- ---------------------------------------------------------------------
CREATE TABLE restaurants (
    id           BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- No ON DELETE action (defaults to RESTRICT): an owner with restaurants cannot be deleted.
    owner_id     BIGINT        NOT NULL,
    name         VARCHAR(120)  NOT NULL,
    description  VARCHAR(1000),
    address      VARCHAR(255)  NOT NULL,
    phone        VARCHAR(20)   NOT NULL,
    image_url    VARCHAR(500),
    -- Denormalised average of reviews (0.0 - 5.0), maintained by the review service (Phase 9)
    -- so listing/sorting by rating does not aggregate the reviews table on every request.
    rating       NUMERIC(2, 1) NOT NULL DEFAULT 0,
    rating_count INTEGER       NOT NULL DEFAULT 0,
    -- is_open: owner toggles it (accepting orders right now?).
    -- active:  admin toggles it (restaurant allowed on the platform at all?).
    is_open      BOOLEAN       NOT NULL DEFAULT TRUE,
    active       BOOLEAN       NOT NULL DEFAULT TRUE,
    -- Optimistic locking counter (JPA @Version), see Restaurant.java.
    version      BIGINT        NOT NULL DEFAULT 0,
    created_at   TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ   NOT NULL DEFAULT now(),

    CONSTRAINT fk_restaurants_owner FOREIGN KEY (owner_id) REFERENCES users (id),
    CONSTRAINT ck_restaurants_rating CHECK (rating BETWEEN 0 AND 5),
    CONSTRAINT ck_restaurants_rating_count CHECK (rating_count >= 0)
);

-- "My restaurants" for an owner, and every ownership check (WHERE id = ? AND owner_id = ?).
CREATE INDEX idx_restaurants_owner_id ON restaurants (owner_id);


-- ---------------------------------------------------------------------
-- menu_items: dishes sold by a restaurant
-- ---------------------------------------------------------------------
CREATE TABLE menu_items (
    id            BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- ON DELETE CASCADE: deleting a restaurant removes its menu.
    restaurant_id BIGINT        NOT NULL,
    -- RESTRICT: a category that is still used by menu items cannot be deleted.
    category_id   BIGINT        NOT NULL,
    name          VARCHAR(120)  NOT NULL,
    description   VARCHAR(500),
    price         NUMERIC(10, 2) NOT NULL,
    image_url     VARCHAR(500),
    available     BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ   NOT NULL DEFAULT now(),

    CONSTRAINT fk_menu_items_restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurants (id) ON DELETE CASCADE,
    CONSTRAINT fk_menu_items_category FOREIGN KEY (category_id) REFERENCES categories (id),
    CONSTRAINT ck_menu_items_price_positive CHECK (price > 0)
);

-- One restaurant cannot list "Veg Pizza" twice (case-insensitive).
-- Because restaurant_id is the FIRST column, this index also serves
-- "WHERE restaurant_id = ?" (load a menu), so a separate
-- idx_menu_items_restaurant_id would be redundant and is deliberately not created.
CREATE UNIQUE INDEX uk_menu_items_restaurant_name ON menu_items (restaurant_id, lower(name));

-- Needed for "restaurants serving category X" (Phase 4) and so the RESTRICT check
-- when deleting a category does not scan the whole menu_items table.
CREATE INDEX idx_menu_items_category_id ON menu_items (category_id);
