-- =====================================================================
-- V4: shopping carts.
--
-- Deliberately NO price column. A cart line stores only WHICH dish and HOW MANY.
-- Every time the cart is shown or checked out, the price is read from
-- menu_items, so:
--   * a client can never inject its own price, and
--   * a price change by the owner is reflected immediately.
-- The price is frozen only when an order is placed (order_items, Phase 6).
-- =====================================================================

CREATE TABLE carts (
    id            BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- One cart per user (UNIQUE). CASCADE: the cart dies with its user.
    user_id       BIGINT      NOT NULL,
    -- The restaurant this cart is currently for; NULL while the cart is empty.
    -- SET NULL: if the restaurant is deleted, its menu items (and so these cart
    -- lines) are deleted by cascade, and the cart simply becomes empty.
    restaurant_id BIGINT,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT uk_carts_user UNIQUE (user_id),
    CONSTRAINT fk_carts_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_carts_restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurants (id) ON DELETE SET NULL
);

CREATE TABLE cart_items (
    id           BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cart_id      BIGINT      NOT NULL,
    -- CASCADE: if the owner deletes a dish, it silently leaves every cart.
    menu_item_id BIGINT      NOT NULL,
    quantity     INTEGER     NOT NULL,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT fk_cart_items_cart FOREIGN KEY (cart_id) REFERENCES carts (id) ON DELETE CASCADE,
    CONSTRAINT fk_cart_items_menu_item FOREIGN KEY (menu_item_id) REFERENCES menu_items (id) ON DELETE CASCADE,
    -- Same dish twice = one line with a bigger quantity, never two lines.
    -- cart_id is the first column, so this index also serves "load the items of cart X".
    CONSTRAINT uk_cart_items_cart_menu_item UNIQUE (cart_id, menu_item_id),
    CONSTRAINT ck_cart_items_quantity CHECK (quantity BETWEEN 1 AND 20)
);

-- Deleting a menu item must find its cart lines (for the cascade) without a full scan.
CREATE INDEX idx_cart_items_menu_item_id ON cart_items (menu_item_id);
