-- =====================================================================
-- V5: orders, order lines (with price snapshots) and status history.
--
-- An order is a historical record. Everything the customer agreed to pay for
-- is COPIED into it at checkout: dish names, unit prices and the delivery
-- address. Later changes to menu_items or addresses therefore never rewrite
-- the past:
--
--   today:    Pizza = 250, customer orders 1  -> order_items: 'Pizza', 250.00 x 1
--   tomorrow: owner changes Pizza to 300       -> the old order still shows 250.00
-- =====================================================================

CREATE TABLE orders (
    id                  BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- RESTRICT (default): customers and restaurants with orders cannot be deleted.
    -- Order history is financial data; accounts are disabled and restaurants deactivated instead.
    user_id             BIGINT        NOT NULL,
    restaurant_id       BIGINT        NOT NULL,
    -- Link to the saved address, for reference only. SET NULL when the customer deletes
    -- that address later; delivery_address below keeps the actual text.
    address_id          BIGINT,
    delivery_address    VARCHAR(600)  NOT NULL,
    status              VARCHAR(30)   NOT NULL,
    subtotal            NUMERIC(10, 2) NOT NULL,
    discount_amount     NUMERIC(10, 2) NOT NULL DEFAULT 0,  -- coupons, Phase 8
    total_amount        NUMERIC(10, 2) NOT NULL,
    cancellation_reason VARCHAR(255),
    -- Optimistic locking: two concurrent status changes can't silently overwrite each other.
    version             BIGINT        NOT NULL DEFAULT 0,
    created_at          TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ   NOT NULL DEFAULT now(),

    CONSTRAINT fk_orders_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_orders_restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurants (id),
    CONSTRAINT fk_orders_address FOREIGN KEY (address_id) REFERENCES addresses (id) ON DELETE SET NULL,
    CONSTRAINT ck_orders_status CHECK (status IN ('PLACED', 'CONFIRMED', 'PREPARING', 'READY_FOR_PICKUP',
                                                  'OUT_FOR_DELIVERY', 'DELIVERED', 'CANCELLED')),
    CONSTRAINT ck_orders_amounts_non_negative CHECK (subtotal >= 0 AND discount_amount >= 0 AND total_amount >= 0),
    -- The database itself refuses an order whose total doesn't add up.
    CONSTRAINT ck_orders_total CHECK (total_amount = subtotal - discount_amount)
);

-- "My orders, newest first": one index serves both the WHERE and the ORDER BY,
-- so PostgreSQL can read the first page directly without sorting all of a user's orders.
CREATE INDEX idx_orders_user_created ON orders (user_id, created_at DESC);
-- Same for the owner dashboard's per-restaurant order list.
CREATE INDEX idx_orders_restaurant_created ON orders (restaurant_id, created_at DESC);
-- For the SET NULL when an address is deleted; partial because most lookups have a value.
CREATE INDEX idx_orders_address_id ON orders (address_id) WHERE address_id IS NOT NULL;
-- No stand-alone index on status: with only 7 distinct values it is rarely selective enough
-- to beat a scan, and every real query also filters by user or restaurant (indexed above).


CREATE TABLE order_items (
    id           BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id     BIGINT        NOT NULL,
    -- Nullable + SET NULL: if the owner later deletes the dish, the order line survives
    -- thanks to the snapshot columns below.
    menu_item_id BIGINT,
    -- Snapshot of the dish at purchase time.
    item_name    VARCHAR(120)  NOT NULL,
    unit_price   NUMERIC(10, 2) NOT NULL,
    quantity     INTEGER       NOT NULL,
    line_total   NUMERIC(10, 2) NOT NULL,
    created_at   TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ   NOT NULL DEFAULT now(),

    CONSTRAINT fk_order_items_order FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE,
    CONSTRAINT fk_order_items_menu_item FOREIGN KEY (menu_item_id) REFERENCES menu_items (id) ON DELETE SET NULL,
    CONSTRAINT ck_order_items_price_positive CHECK (unit_price > 0),
    CONSTRAINT ck_order_items_quantity CHECK (quantity BETWEEN 1 AND 20),
    CONSTRAINT ck_order_items_line_total CHECK (line_total = unit_price * quantity)
);

CREATE INDEX idx_order_items_order_id ON order_items (order_id);
CREATE INDEX idx_order_items_menu_item_id ON order_items (menu_item_id) WHERE menu_item_id IS NOT NULL;


-- ---------------------------------------------------------------------
-- order_status_history: append-only log of every status change.
-- Powers the tracking timeline ("Placed 12:01, Confirmed 12:03, ...") and
-- answers "who cancelled this order, and when?".
-- ---------------------------------------------------------------------
CREATE TABLE order_status_history (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id    BIGINT       NOT NULL,
    from_status VARCHAR(30),                -- NULL for the initial PLACED entry
    to_status   VARCHAR(30)  NOT NULL,
    changed_by  BIGINT,
    note        VARCHAR(255),
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT fk_order_status_history_order FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE,
    CONSTRAINT fk_order_status_history_user FOREIGN KEY (changed_by) REFERENCES users (id) ON DELETE SET NULL
);

CREATE INDEX idx_order_status_history_order_id ON order_status_history (order_id);
