-- =====================================================================
-- V6: payments.
--
-- orders gets two columns:
--   payment_method  chosen at checkout: CARD | UPI | CASH_ON_DELIVERY
--   payment_status  the order's money state: PENDING | PAID | REFUNDED
--
-- payments holds every payment ATTEMPT (a declined card followed by a successful
-- retry = 2 rows), so the full money trail of an order is always visible.
-- =====================================================================

-- Adding NOT NULL columns to a table that already has rows: give them a DEFAULT so
-- existing rows get a value, then DROP the default so new code must always set one.
ALTER TABLE orders ADD COLUMN payment_method VARCHAR(20) NOT NULL DEFAULT 'CASH_ON_DELIVERY';
ALTER TABLE orders ADD COLUMN payment_status VARCHAR(20) NOT NULL DEFAULT 'PENDING';
ALTER TABLE orders ALTER COLUMN payment_method DROP DEFAULT;
ALTER TABLE orders ALTER COLUMN payment_status DROP DEFAULT;
ALTER TABLE orders ADD CONSTRAINT ck_orders_payment_method
    CHECK (payment_method IN ('CARD', 'UPI', 'CASH_ON_DELIVERY'));
ALTER TABLE orders ADD CONSTRAINT ck_orders_payment_status
    CHECK (payment_status IN ('PENDING', 'PAID', 'REFUNDED'));

CREATE TABLE payments (
    id                    BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- RESTRICT (default): payment records are financial history and are never cascaded away.
    order_id              BIGINT        NOT NULL,
    -- Always copied from orders.total_amount on the server; never taken from the client.
    amount                NUMERIC(10, 2) NOT NULL,
    method                VARCHAR(20)   NOT NULL,
    status                VARCHAR(20)   NOT NULL,
    -- Which gateway handled it ('SIMULATED', 'CASH', later 'RAZORPAY', ...).
    provider              VARCHAR(30)   NOT NULL,
    -- The gateway's id for the charge; used for refunds and reconciliation.
    transaction_reference VARCHAR(100),
    refund_reference      VARCHAR(100),
    failure_reason        VARCHAR(255),
    created_at            TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at            TIMESTAMPTZ   NOT NULL DEFAULT now(),

    CONSTRAINT fk_payments_order FOREIGN KEY (order_id) REFERENCES orders (id),
    CONSTRAINT uk_payments_transaction_reference UNIQUE (transaction_reference),
    CONSTRAINT ck_payments_amount CHECK (amount >= 0),
    CONSTRAINT ck_payments_method CHECK (method IN ('CARD', 'UPI', 'CASH_ON_DELIVERY')),
    CONSTRAINT ck_payments_status CHECK (status IN ('PENDING', 'SUCCESS', 'FAILED', 'REFUNDED', 'CANCELLED'))
);

CREATE INDEX idx_payments_order_id ON payments (order_id);

-- THE double-charge guard: per order, at most ONE payment that is in progress or has taken
-- money. Two "Pay" clicks at the same moment both try to INSERT a PENDING row; the database
-- lets exactly one through. Failed/cancelled attempts are excluded, so retries still work.
CREATE UNIQUE INDEX uk_payments_one_active_per_order ON payments (order_id)
    WHERE status IN ('PENDING', 'SUCCESS', 'REFUNDED');

-- Backfill: orders placed before this migration were cash-on-delivery (the default above).
-- Give each one the payment row it would have had, matching its current state.
INSERT INTO payments (order_id, amount, method, status, provider, transaction_reference)
SELECT id,
       total_amount,
       'CASH_ON_DELIVERY',
       CASE status WHEN 'DELIVERED' THEN 'SUCCESS' WHEN 'CANCELLED' THEN 'CANCELLED' ELSE 'PENDING' END,
       'CASH',
       CASE status WHEN 'DELIVERED' THEN 'COD-' || id END
FROM orders;

UPDATE orders SET payment_status = 'PAID' WHERE status = 'DELIVERED';
