-- =====================================================================
-- V7: coupons.
--
--   PERCENTAGE    SAVE10:  10% off, optionally capped by maximum_discount
--   FIXED_AMOUNT  FLAT100: 100 off
--
-- used_count is only ever changed by one atomic conditional UPDATE
-- (CouponRepository.tryRedeem), and the CHECK below makes over-redemption
-- impossible even if application code were wrong.
-- =====================================================================

CREATE TABLE coupons (
    id                   BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Stored upper-case; customers may type "save10", which is normalised before lookup.
    code                 VARCHAR(30)   NOT NULL,
    description          VARCHAR(255),
    discount_type        VARCHAR(20)   NOT NULL,
    discount_value       NUMERIC(10, 2) NOT NULL,
    minimum_order_amount NUMERIC(10, 2) NOT NULL DEFAULT 0,
    maximum_discount     NUMERIC(10, 2),           -- NULL = no cap
    usage_limit          INTEGER,                  -- NULL = unlimited
    used_count           INTEGER       NOT NULL DEFAULT 0,
    starts_at            TIMESTAMPTZ,              -- NULL = valid immediately
    expires_at           TIMESTAMPTZ   NOT NULL,
    active               BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at           TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at           TIMESTAMPTZ   NOT NULL DEFAULT now(),

    CONSTRAINT uk_coupons_code UNIQUE (code),
    CONSTRAINT ck_coupons_code_upper CHECK (code = upper(code)),
    CONSTRAINT ck_coupons_type CHECK (discount_type IN ('PERCENTAGE', 'FIXED_AMOUNT')),
    CONSTRAINT ck_coupons_value_positive CHECK (discount_value > 0),
    CONSTRAINT ck_coupons_percentage_max_100 CHECK (discount_type <> 'PERCENTAGE' OR discount_value <= 100),
    CONSTRAINT ck_coupons_minimum_non_negative CHECK (minimum_order_amount >= 0),
    CONSTRAINT ck_coupons_maximum_positive CHECK (maximum_discount IS NULL OR maximum_discount > 0),
    CONSTRAINT ck_coupons_usage_limit_positive CHECK (usage_limit IS NULL OR usage_limit > 0),
    -- Backstop: the counter can never exceed the limit, whatever the application does.
    CONSTRAINT ck_coupons_used_within_limit CHECK (used_count >= 0 AND (usage_limit IS NULL OR used_count <= usage_limit)),
    CONSTRAINT ck_coupons_dates CHECK (starts_at IS NULL OR starts_at < expires_at)
);

-- Orders remember which coupon they used: the link (for analytics and releasing a use on
-- cancel) and a snapshot of the code (history reads correctly even if a coupon changes later).
-- RESTRICT (default): a coupon that has been used can't be deleted, only deactivated.
ALTER TABLE orders ADD COLUMN coupon_id BIGINT;
ALTER TABLE orders ADD COLUMN coupon_code VARCHAR(30);
ALTER TABLE orders ADD CONSTRAINT fk_orders_coupon FOREIGN KEY (coupon_id) REFERENCES coupons (id);
CREATE INDEX idx_orders_coupon_id ON orders (coupon_id) WHERE coupon_id IS NOT NULL;
