-- =====================================================================
-- V8: reviews.
--
-- A review is tied to ONE delivered order. That single rule gives us:
--   * only real customers can review (you need an order),
--   * only after the food arrived (the order must be DELIVERED; checked in the service),
--   * no duplicates (UNIQUE order_id), while a regular customer can still review
--     each of their orders separately.
--
-- restaurants.rating / rating_count (from V1) cache the average, so listing and
-- sorting restaurants by rating never has to aggregate this table.
-- =====================================================================

CREATE TABLE reviews (
    id            BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT        NOT NULL,
    restaurant_id BIGINT        NOT NULL,
    order_id      BIGINT        NOT NULL,
    rating        INTEGER       NOT NULL,
    comment       VARCHAR(1000),
    created_at    TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ   NOT NULL DEFAULT now(),

    CONSTRAINT fk_reviews_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_reviews_restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurants (id),
    CONSTRAINT fk_reviews_order FOREIGN KEY (order_id) REFERENCES orders (id),
    -- One review per order, enforced by the database even if two requests race.
    CONSTRAINT uk_reviews_order UNIQUE (order_id),
    CONSTRAINT ck_reviews_rating CHECK (rating BETWEEN 1 AND 5)
);

-- "Reviews of restaurant X, newest first" (public, paged), and the SUM/COUNT recalculation.
CREATE INDEX idx_reviews_restaurant_created ON reviews (restaurant_id, created_at DESC);
