package com.foodflow.entity;

import jakarta.persistence.Column;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.MappedSuperclass;
import lombok.Getter;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;
import org.hibernate.proxy.HibernateProxy;

import java.time.Instant;

/**
 * Columns shared by every table: id, created_at, updated_at.
 *
 * <p>{@code @MappedSuperclass} is not a table itself; its fields are copied into each subclass's table.
 */
@Getter
@MappedSuperclass
public abstract class BaseEntity {

    /*
     * IDENTITY = PostgreSQL generates the id on INSERT (GENERATED BY DEFAULT AS IDENTITY).
     * Trade-off: Hibernate must run each INSERT immediately to learn the id, so it cannot
     * batch inserts. SEQUENCE with allocationSize would allow batching; IDENTITY is chosen
     * for simplicity because our write volume per request is small.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @CreationTimestamp
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    @UpdateTimestamp
    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;

    /*
     * Entity identity = database id. Two rules make this safe with Hibernate:
     *  1. Compare the *real* class, unwrapping lazy-loading proxies. A proxy is a generated
     *     subclass (e.g. User$HibernateProxy$abc), so getClass() alone would say a proxy and
     *     the real object are different. Reading the class from the proxy does not load it.
     *  2. A new, unsaved entity (id == null) is only equal to itself.
     *
     * hashCode is constant per class (not based on id) so an entity placed in a HashSet
     * before being saved is still found after save assigns its id.
     *
     * Lombok's @Data / @EqualsAndHashCode are deliberately NOT used on entities: they compare
     * every field, trigger lazy loading, and recurse forever across bidirectional relations.
     */
    @Override
    public final boolean equals(Object other) {
        if (this == other) {
            return true;
        }
        if (other == null || effectiveClass(this) != effectiveClass(other)) {
            return false;
        }
        Long thisId = getId();
        return thisId != null && thisId.equals(((BaseEntity) other).getId());
    }

    @Override
    public final int hashCode() {
        return effectiveClass(this).hashCode();
    }

    private static Class<?> effectiveClass(Object entity) {
        return entity instanceof HibernateProxy proxy
                ? proxy.getHibernateLazyInitializer().getPersistentClass()
                : entity.getClass();
    }
}
